### ISSUE TITLE
belongs_to relation generates wrong method definition

### ISSUE THREAD

**Issue by isaacwecode** [axyr/silverstripe-ideannotator#65] opened 2016-05-02 10:28 UTC
```
    private static /** @noinspection PhpUnusedPrivateFieldInspection */
        $belongs_to = array(
        'Customer' => 'Customer.Manager',
    );
```
generates

` * @method Customer.Manager $Customer`

I would expect it to generate

` * @method Customer Customer()`

instead.

**Comment by Firesphere** [comment] 2016-05-02 10:42
Indeed, it seems dot-notation isn't detected at this moment.
@axyr If you don't have time, I can have a look at it this friday. Let me know?

**Comment by Firesphere** [comment] 2016-05-02 10:54
I would actually expect it to be a manager. Customer is the relation, but manager would be the endpoint.

At this moment, dot-notation is not supported. Sorry, will have a look if I have the time. Otherwise, I suspect @axyr will do before me ;)

**Comment by isaacwecode** [comment] 2016-05-02 11:04
See https://docs.silverstripe.org/en/3.3/developer_guides/model/relations/
```
class Team extends DataObject {

    private static $has_one = array(
        'Coach' => 'Coach'
    );
}

class Coach extends DataObject {

    private static $belongs_to = array(
        'Team' => 'Team.Coach'
    );
}
```
It should return a Team not a Coach.

Also note the dollar sign in the generated method definition that is unrelated to the dot notation.

**Comment by Firesphere** [comment] 2016-05-02 11:08
Hmmm, so it's just splitting on dot-notation. That could work.
I'm in the middle of rewriting security. @axyr got time? Or @isaacwecode feel free to create a pull request.

**Comment by axyr** [comment] 2016-05-02 11:19
Lazy (we)coders ;) ...

Will take a look at it. Maybe later this week if I find the time. But PR would be nice..

**Comment by Firesphere** [comment] 2016-05-03 06:52
Hey, I don't work at we::code!

**Comment by axyr** [comment] 2016-05-03 08:02
;) i know..

Fixed with https://github.com/axyr/silverstripe-ideannotator/commit/8a0aa6f8055cb1fc400d73d5acd74ae2f6243f0a

Could not reproduce the $ sign in the generated tag though?

* @method Customer.Manager $Customer

**Closed by axyr** 2016-05-03 08:02 UTC
Labels: bug
