### ISSUE TITLE
Feature: Post @todo's to issue tracker

### ISSUE THREAD

**Issue by pandauxstudio** [axyr/silverstripe-ideannotator#30] opened 2016-03-16 09:56 UTC
Would be nice if dev/build task would generate tasks in issue tracker via API, would be nice if this configurable in configs.

**Comment by Firesphere** [comment] 2016-03-16 10:11
For this, I would be okay, but I am not building it inside this module. The actual hook to the issue tracker should be a separate module. Adding API hooks like that into this module would steer away from it's core functionality.
Optionally, a quick-and-dirty first option would parse todo's and store them in a DO for easy overview of all that's marked as todo.
For Jira/BitBucket, I've been busy trying to come up with a way to hook it into SilverStripe.

**Comment by axyr** [comment] 2016-03-16 10:15
This is beyond the scope of this module.
intelli idea already can summarise todo's from code...

The purpose is to provide autocompletion and discovery in an IDE.

**Comment by axyr** [comment] 2016-03-28 07:59
same as #31 . I see this of 'Out of scope'

**Closed by axyr** 2016-03-28 07:59 UTC

**Comment by Firesphere** [comment] 2016-03-28 08:19
Agreed. Although a nice feature, and parsing the todo's shouldn't be that hard, the problem is in the amount of issue-trackers around.
Ok, it works with Jira, but not with BitBucket. etc.
It's quite a reach on scope of this module. As mentioned in the doc generation, there needs to be a uniform, trustworthy, external module before this is worth looking at.
